/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pac.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pac.control.c_koneksi;
import pac.control.controllerToko;
import pac.model.m_toko;

/**
 *
 * @author Smktelkomm
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        cbjenis = new javax.swing.JComboBox<>();
        cbKategoriBrg = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        CbCariKategori = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Btn_Keluar = new javax.swing.JButton();
        Btn_Simpan = new javax.swing.JButton();
        Btn_Ubah = new javax.swing.JButton();
        Btn_Clean = new javax.swing.JButton();
        Btn_Clear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(75, 169, 210));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gisha", 1, 18)); // NOI18N
        jLabel1.setText("Data Barang di Toko");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 10, 230, 80);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 20, 160, 30);

        jLabel4.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel4.setText("Admin Toko :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 100);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel3.setText("Harga");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 190, 90, 30);

        jLabel5.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel5.setText("Kode Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 30, 90, 30);

        jLabel6.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel6.setText("Nama Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 90, 30);

        jLabel7.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel7.setText("Kategori Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 110, 90, 30);

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtharga);
        txtharga.setBounds(120, 190, 350, 30);

        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        jPanel2.add(txtkode);
        txtkode.setBounds(120, 30, 350, 30);

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel2.add(txtnama);
        txtnama.setBounds(120, 70, 350, 30);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Satuan" }));
        jPanel2.add(cbjenis);
        cbjenis.setBounds(120, 150, 350, 30);

        cbKategoriBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Baranglain" }));
        cbKategoriBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriBrgActionPerformed(evt);
            }
        });
        jPanel2.add(cbKategoriBrg);
        cbKategoriBrg.setBounds(120, 110, 350, 30);

        jLabel9.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel9.setText("Jenis Packaging");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 150, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 100, 540, 250);

        CbCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Baranglain" }));
        CbCariKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCariKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(CbCariKategori);
        CbCariKategori.setBounds(280, 360, 130, 30);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        Tabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori ", "Packaging", "Harga"
            }
        ));
        jScrollPane1.setViewportView(Tabel1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(30, 0, 520, 90);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 400, 780, 270);

        jLabel8.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        jLabel8.setText("Pencarian Berdasarkan Kategori Makanan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 360, 230, 30);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(420, 360, 73, 30);

        Btn_Keluar.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        Btn_Keluar.setText("Exit");
        Btn_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KeluarActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Keluar);
        Btn_Keluar.setBounds(40, 190, 110, 30);

        Btn_Simpan.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        Btn_Simpan.setText("Save");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Simpan);
        Btn_Simpan.setBounds(40, 30, 110, 30);

        Btn_Ubah.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        Btn_Ubah.setText("Change");
        Btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UbahActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Ubah);
        Btn_Ubah.setBounds(40, 70, 110, 30);

        Btn_Clean.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        Btn_Clean.setText("Clean");
        Btn_Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CleanActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Clean);
        Btn_Clean.setBounds(40, 110, 110, 30);

        Btn_Clear.setFont(new java.awt.Font("Gisha", 0, 12)); // NOI18N
        Btn_Clear.setText("Clear");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Clear);
        Btn_Clear.setBounds(40, 150, 110, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(590, 100, 180, 250);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 360, 73, 30);

        setBounds(0, 0, 816, 713);
    }// </editor-fold>//GEN-END:initComponents

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void CbCariKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCariKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCariKategoriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KeluarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_KeluarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ctoko.CariKategori();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UbahActionPerformed
        ctoko.Ubah();
        ctoko.isiTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_UbahActionPerformed

    private void Btn_CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CleanActionPerformed
        ctoko.Reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CleanActionPerformed

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
        ctoko.Hapus();
        ctoko.isiTable();
         // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void cbKategoriBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKategoriBrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Clean;
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Keluar;
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JButton Btn_Ubah;
    private javax.swing.JComboBox<String> CbCariKategori;
    private javax.swing.JTable Tabel1;
    private javax.swing.JComboBox<String> cbKategoriBrg;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtKode(){
        return txtkode;
    }
    public JTextField getTxtNama(){
        return txtnama;
    }
    public JTextField getTxtHarga(){
        return txtharga;
    }
    public JComboBox getCbKategori(){
        return cbKategoriBrg;
    }
    public JComboBox getCbJenis(){
        return cbjenis;
    }
    public JComboBox getCbCariKategori(){
        return CbCariKategori;
    }
    public JButton getButtonHapus(){
        return Btn_Clear;
    }
    
    public JButton getButtonBersih(){
        return Btn_Clean;
    }
    public JButton getButtonSimpan(){
        return Btn_Simpan;
    }
    public JButton getButtonUbah(){
        return Btn_Ubah;
    }
    public JButton getButtonKeluar(){
        return Btn_Keluar;
    }
    public JTable getTableData(){
        return Tabel1;
    }


}


